### ISSUE TITLE
why can't i see the 'print'

### ISSUE THREAD

**Issue by CoolCaicaixian** [cookiecutter-flask/cookiecutter-flask#2084]
<img width="897" alt="截屏2024-05-23 18 43 37" src="https://github.com/cookiecutter-flask/cookiecutter-flask/assets/55055281/093611e1-6643-443f-a22e-f677ba259986">
👆

**Comment by CoolCaicaixian** [comment]
use **_current_app.logger.info_**  can see the log.
but why _**print**_ can not ?

**Comment by jamescurtin** [comment]
`print` output to stdout is probably being buffered. In general, using the logger is the preferred option, but if printing needed, you have a few options:

1. Set the `PYTHONUNBUFFERED` environment variable
2. Manually flush: `print("foo", flush=True)`
3. Print to stderr instead of stdout, as it doesn't get buffered `import sys; print("foo", file=sys.stderr)`
