### ISSUE TITLE
Please add example function in script.js

### ISSUE THREAD

**Issue by azzamsa** [cookiecutter-flask/cookiecutter-flask#576]
I tried many ways but can't get it work properly. I still can't call any js function that I put in `/assets/js/script.js`. I belive this is because I don't have good foundation in webpack. 

I've tried several suggestion. e.g [1](https://github.com/webpack/webpack/issues/2171), [2](https://stackoverflow.com/a/43285831/6000005), [3](https://stackoverflow.com/a/56794331/6000005). Even I've tried to mimic my [PR to saka-key](https://github.com/lusakasa/saka-key/pull/238/files) that use webpack, but it failed.

How to put & call function properly using webpack in flask-coockieclutter ?

Please add simple example: .e.g

``` js
% This is in script.js
function changeYear(){
  document.getElementById("year").innerHTML = new Date().getFullYear();
}

```

```django
<!-- this is in members.html -->
  <div class="container">
        <p>Hai user, this year is:<span id="year">2018</span></p>
    </div>
```

Thanks.

PS: I still can't call any function defined in `script.py`, any help will be appreciated.

**Comment by azzamsa** [comment]
This is my current workaround **(but limited to files in `main.js`, can't be in `script.js`)**

1) Add `library` for entry point

```diff
modified   webpack.config.js
@@ -31,6 +31,7 @@ module.exports = {
     publicPath: `${publicHost}/static/build/`,
     filename: '[name].[hash].js',
     chunkFilename: '[id].[hash].js',
+    library: 'Main'
   },
   resolve: {
     extensions: ['.js', '.jsx', '.css'],

```

2) add exports after functions

```diff
 require('./script.js');
+
+function hai () {
+  console.log('hello world');
+}
+
+module.exports = {
+  hai: hai,
+};
```

3) call with entry point in templates

```diff
 <script>
   window.onload = function () {
+    Main.hai();
   };
 </script> 
{% endblock %}
```

Credit: [Calling webpacked code from outside (HTML script tag)](https://stackoverflow.com/a/34361312/6000005)

**Comment by jamescurtin** [comment]
Hi @azzamsa, 

Any code in `scripts.js` is bundled up by webpack. The bundled code is what's available within the app, rather than the raw `script.js` file. You can find the bundled code using your browser's developer tools (it is named `main_js.{{hash}}.js`).

![image](https://user-images.githubusercontent.com/10189269/66273767-fd80af00-e844-11e9-8743-ef5ae1a76ec4.png)
-------------------
To demo that the bundling functionality works, I created a fresh copy of the app, added the following code and started up the app:
```javascript
// assets/js/script.js
function UpdateFooter() {
  document.querySelector(".company").innerHTML = "Footer Updated!";
}

setTimeout(UpdateFooter, 2000);
```

Here's an example of this in action (you'll see the copyright notice at the bottom is updated)
![demo_gif](https://user-images.githubusercontent.com/10189269/66273893-84825700-e846-11e9-81ed-57b3666996bf.gif)


-------------

For additional context:

**Where is the bundled javascript loaded into the page?**
The flask template uses the [`main_js`](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/ba333e67b4408e834310f316b3df8b499853442e/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/templates/layout.html#L59) javascript_tag to get the bundled script, and automatically builds a `<script>` tag.

**How is the `main_js` tag assigned to the file `assets/js/main.js`?**
[Here](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/ba333e67b4408e834310f316b3df8b499853442e/%7B%7Bcookiecutter.app_name%7D%7D/webpack.config.js#L22)



Closing out for now, but let me know if you have any additional questions!
