### ISSUE TITLE
Failed to identify the backend framework being used, why is it using both Node.js and Flask in the backend?

### ISSUE THREAD

**Issue by shravankumar9892** [cookiecutter-flask/cookiecutter-flask#593]
Being new to backend development, I'm really confused, would appreciate a simple explanation for it.

**Comment by luismanson** [comment]
Hello, since development is not my thing, I cant explain it right, but:
_take this with a grain of salt_:

- Node is helping with static content and the front end code (downloading js libs, minify, compress, etc)). 
- Flask is running the backend.

Please, read here in case I got it wrong:
https://medium.com/the-node-js-collection/modern-javascript-explained-for-dinosaurs-f695e9747b70

**Comment by jamescurtin** [comment]
You got it! Flask is the main framework used by this project. The primary role of Node is to run [webpack](https://webpack.js.org/) to do all of the things luismanson noted. You can also use it to lint the javascript in your project for syntax/formatting errors.
