### ISSUE TITLE
/var/lib/docker/volumes/my_project_node-modules/_data/.bin/acorn: file exists

### ISSUE THREAD

**Issue by stodge** [cookiecutter-flask/cookiecutter-flask#758]
I ran `docker-compose up`, but it failed after a while, because I already had something running on port 5000. I took docker-compose down, removed the volumes and images and tried again.

However it failed with:

```
Creating my_project_manage_1     ... error

Creating my_project_flask-prod_1 ... error
o_node-modules/_data/.bin/acorn: file exists
Creating my_project_flask-dev_1  ... done
ERROR: for my_project_flask-prod_1  Cannot create container for service flask-prod: failed to create symlink: /var/lib/docker/volumes/my_project_node-modules/_data/.bin/acorn: symlink ../acorn/bin/acorn /var/lib/docker/volumes/my_project_node-modules/_data/.bin/acorn: file exists

ERROR: for manage  Cannot create container for service manage: failed to create symlink: /var/lib/docker/volumes/my_project_node-modules/_data/.bin/acorn: symlink ../acorn/bin/acorn /var/lib/docker/volumes/my_project_node-modules/_data/.bin/acorn: file exists

ERROR: for flask-prod  Cannot create container for service flask-prod: failed to create symlink: /var/lib/docker/volumes/my_project_node-modules/_data/.bin/acorn: symlink ../acorn/bin/acorn /var/lib/docker/volumes/my_project_node-modules/_data/.bin/acorn: file exists
ERROR: Encountered errors while bringing up the project.
```

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [X] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [X] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [X] `yes`</li><li>- [ ] `no`</li></ul>                      |

**Comment by jamescurtin** [comment]
Hi @stodge, this isn't a bug with the project itself, there's something wrong with the volumes from the project. When stopping a project (e.g. so that you can re-start it on a different port), it is sufficient to just run `docker-compose down` without removing volumes or images.

I'd recommend checking the [docker documentation on removing volumes](https://docs.docker.com/engine/reference/commandline/volume_rm/) to make sure the old volumes were fully removed then try starting up the project again. 

I also see from the terminal output that both the dev and prod versions of the application are being started simultaneously, which will result in errors. You'd want to run only one at a time using the commands described in the project README, e.g. `docker-compose up flask-dev` or `docker-compose up flask-prod`.

**Comment by stodge** [comment]
Ok, thanks again. :)

**Comment by stodge** [comment]
Do you have a gitter channel for questions, so I don't fill your issues list with my mistakes?
