### ISSUE TITLE
Debug (e.g., with pydev)

### ISSUE THREAD

**Issue by valhuber** [cookiecutter-flask/cookiecutter-flask#813]
First, thanks for this... new to Python, great to have a template to point me in the right direction.

Two questions:

1. I have also explored pydev, for its debugger. Any provisions to debug Cookiecutter-flask apps (pydev or other)?

2. Also, why the node dependency?  Do these apps not run under flask development server (which pydev seems to be able to debug)?

**Comment by jamescurtin** [comment]
Hi @valhuber:

When I debug, I typically use `pdb` or `pdbpp`; I don't have experience with the debuggers for particular IDEs.

Node is used because the project leverages webpack for bundling frontend assets. In order to auto-reload changes, the application runs under the node development server.

If you'd prefer to use the flask development server, feel free to update your project to do so: once you build the assets once, the application will work just fine if you start up flask with a command like `flask run --host=0.0.0.0` so you can leverage the built-in debugging functionality for your IDE. If you changed any resources, you'd have to re-bundle for the changes to register in the app---but if you aren't modifying resources often, that shouldn't be a big deal
