### ISSUE TITLE
bug Login route in nav.html for subdirectory apps

### ISSUE THREAD

**Issue by glyg** [cookiecutter-flask/cookiecutter-flask#923]
Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [ ] `3.8`</li><li>- [X] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [X] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [X] `yes`</li><li>- [ ] `no`</li></ul>                      |

I'm making an app that runs on a sub-directory of my website (https://example.com/myapp/)

Due to the `action="/"` on the login form in [nav.html](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/templates/nav.html#L34), when the user tries to login the POST is directed to the website root directory, which is a 404 for the app, and prevents logging to go through:

```
flask-dev_1   | [FLASK] 172.24.9.25 - - [09/Oct/2020 14:34:52] "POST / HTTP/1.1" 404
```

Removing the slash and putting an empty string here fixes the problem - although I'm not sure it is the right thing to do (maybe get `request.path` instead?

Thanks for the cookie cutter for all the rest, it's a huge time saver!

I can open a PR if you need

Best

Guillaume

**Comment by jamescurtin** [comment]
Hi @glyg!

This is an issue for you because your application is not being served at the domain root. Setting `action=""` partially works, but would not be the best implementation. This is because when the `action` is empty, the `POST` payload is sent to the current page. Login POST requests are handled by the root endpoint, so all requests will be sent to the right place as long as you log in from the home page. You will encounter problems, though, when you try to log in from any other page. If you go to the "about" page, for example, and try to log in, the form with post the data to the `/about` endpoint, which doesn't allow POST requests and return an error code.

The alternative is to use `jinja` template functions to template in the correct url. The correct one for this situation is `{{ url_for('public.home') }}` (you can find a few other places where it's used to see what value it returns). This will be the most reliable approach, as it doesn't rely on any hardcoded values. If you wanted to put up a PR to make this change, I'd be more than happy to merge it in!

**Comment by glyg** [comment]
Thanks for the response,

PR follows :)

**Comment by jamescurtin** [comment]
🎉 Sounds great! A PR would be very welcome. 😄
