### ISSUE TITLE
Local folder as volumes

### ISSUE THREAD

**Issue by govindkelkar** [cookiecutter-flask/cookiecutter-flask#963]
I am using docker-compose. I want to mount local folders as volumes.
I used the following syntax:
**x-default-volumes:
  &nbsp;  &nbsp;volumes:
  &nbsp;  &nbsp;  &nbsp;  &nbsp;- ./uploads:/app/uploads
  &nbsp;  &nbsp;  &nbsp;  &nbsp;- ./rawdata:/app/rawdata**
And under 
**volumes:
 &nbsp;  &nbsp;rawdata:
 &nbsp;  &nbsp;uploads:**
Under rawdata I have logs folder in which exists the app.log. the docker-compose up flask-dev gives me the error that it can not find file '/app/rawdata/logs/app.log'. This means the volume is not getting attached.

**Comment by jamescurtin** [comment]
Hi @govindkelkar: this question is related to Docker functionality rather than this project itself, so I will close this issue.

You might want to read up on [bind mounts](https://docs.docker.com/storage/bind-mounts/) versus [volumes](https://docs.docker.com/storage/volumes/), as up define `rawdata` and `uploads` volumes, but are using bind mounts to attach a local directory to the container.
